<a href="https://colab.research.google.com/github/Kotarosz727/my_python/blob/main/01_%E9%87%8D%E5%9B%9E%E5%B8%B0%E5%88%86%E6%9E%90%E3%81%AE%E5%AE%9F%E8%A3%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [ ]:
X = np.array([[1,2], [3,4]])
print(X)

[[1 2]
 [3 4]]


In [ ]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [ ]:
# 逆行列
# linear algebra:線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# 行列積
np.dot(X, X_inv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])