<a href="https://colab.research.google.com/github/Kotarosz727/my_python/blob/main/01_%E9%87%8D%E5%9B%9E%E5%B8%B0%E5%88%86%E6%9E%90%E3%81%AE%E5%AE%9F%E8%A3%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np

In [51]:
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [52]:
X = np.array([[1,2], [3,4]])
print(X)

[[1 2]
 [3 4]]


In [53]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [54]:
# 逆行列
# linear algebra:線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [55]:
# 行列積
np.dot(X, X_inv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

# ** Scikit-learnでの実装**

In [56]:
import sklearn

In [57]:
X = np.array([
      [1,2,3],
      [1,2,5],
      [1,3,4],
      [1,5,9]
     ])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [58]:
y = np.array([
              [1],
              [5],
              [6],
              [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [59]:
# 重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [60]:
# モデルの宣言
# model = LinearRegression()
model = LinearRegression(fit_intercept=False)

In [61]:
# モデルの学習←パラメーターの調整
model.fit(X, y)

LinearRegression(fit_intercept=False)

In [62]:
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [64]:
model.intercept_

0.0

In [66]:
# 予測精度←決定係数
model.score(X, y)

0.6923076923076924

In [67]:
# 予測値の計算
x = np.array([
              [1,2,3]
])

In [69]:
y_pred = model.predict(x)
y_pred

array([[3.]])