<a href="https://colab.research.google.com/github/Kotarosz727/my_python/blob/main/hoge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

X = np.array([
      [1,2,3],
      [1,2,5],
      [1,3,4],
      [1,5,9]
     ])
print(X)

y = np.array([
              [1],
              [5],
              [6],
              [8]
])
print(y)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]
[[1]
 [5]
 [6]
 [8]]


In [ ]:
XT = X.T

In [ ]:
XtX = np.dot(XT, X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [ ]:
XtX_inv = np.linalg.inv(XtX)

In [ ]:
Xty = np.dot(XT, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [ ]:
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]
